spring:
  profiles:
    active: db, core, api
  message:
    encoding: UTF-8

server:
  port: 8080

logging:
  level:
    root:  ERROR
    org.springframework:  ERROR
    org.mybatis:  ERROR
    com.cloudDemo.core:  ERROR
    com.cloudDemo.db:  ERROR
    com.cloudDemo.api:  ERROR
    com.cloudDemo:  ERROR